---
default:
  MAINTENANCE_MODE: null
  ALLOWED_HOSTS: []
  DEBUG: false
  LOGGING_CONFIG: null
  LOGGING:
    disable_existing_loggers: false
    formatters:
      console:
        format: "%(asctime)s %(name)s %(levelname)s %(lineno)d %(funcName)s : %(message)s"
      django:
        (): django.utils.log.ServerFormatter
        format: "[{server_time}] {message}"
        style: "{"
    handlers:
      console:
        class: logging.StreamHandler
        formatter: console
      django:
        class: logging.StreamHandler
        formatter: django
    loggers:
      '':
        level: INFO
        handlers:
        - console
      watchtower:
        level: INFO
        handlers:
        - console
        propagate: false
      django:
        level: INFO
        handlers:
        - django
        propagate: false
      rest:
        level: INFO
        handlers:
        - console
        propagate: false
    version: 1
development:
  ALLOWED_HOSTS:
  - '*'
  DEBUG: true
  INSTALLED_APPS:
    - django_extensions
    - dynaconf_merge_unique
  LOGGING:
    dynaconf_merge: true
    handlers:
      console:
        class: logging.StreamHandler
        formatter: console
      django:
        class: logging.StreamHandler
        formatter: django
    loggers:
      '':
        level: INFO
        handlers:
        - console
      watchtower:
        level: DEBUG
        handlers:
        - console
        propagate: false # required to avoid double logging with root logger
      rest:
        level: INFO
        handlers:
        - console
        propagate: false # required to avoid double logging with root logger
      django:
        handlers:
        - django
        level: INFO
        propagate: false
  DATABASES:
    default:
      ENGINE: django.db.backends.sqlite3
      NAME: db/dev.sqlite3
testing:
  DEBUG: true
  ALLOWED_HOSTS:
  - '*'
  DATABASES:
    default:
      ENGINE: django.db.backends.sqlite3
      NAME: watchtower/db/testing.sqlite3
maintenance:
  #Maintenances Mode
  # If True the maintenance-mode will be activated
  MAINTENANCE_MODE: true
staging:
  ALLOWED_HOSTS:
  - staging.watchtower.com
production:
  ALLOWED_HOSTS:
  - watchtower.com
#  DATABASES:
#    default:
#      ENGINE: django.contrib.gis.db.backends.postgis
#      NAME: wachturm
#      USER: wachturm
#      PASSWORD: ??????? in .secret.yaml
#      HOST: localhost
#      PORT: 5432
  LOGGING:
    dynaconf_merge: true
    handlers:
      console:
        level: WARNING
        class: logging.StreamHandler
        formatter: console
      django:
        level: WARNING
        class: logging.StreamHandler
        formatter: django
    loggers:
      '':
        level: WARNING
        handlers:
          - console
      rest:
        level: WARNING
        handlers:
          - django
        propagate: false
      django:
        handlers:
          - django
        level: WARNING
        propagate: false