[development]
BASE_DIR = "/Users/ouss/Documents/workspace/Watchtower/watchtower"
DEBUG = true
ALLOWED_HOSTS = []
INSTALLED_APPS = [ "django.contrib.admin", "django.contrib.auth", "django.contrib.contenttypes", "django.contrib.sessions", "django.contrib.messages", "django.contrib.staticfiles", "django_extensions", "wachturm",]
MIDDLEWARE = [ "django.middleware.security.SecurityMiddleware", "django.contrib.sessions.middleware.SessionMiddleware", "django.middleware.common.CommonMiddleware", "django.middleware.csrf.CsrfViewMiddleware", "django.contrib.auth.middleware.AuthenticationMiddleware", "django.contrib.messages.middleware.MessageMiddleware", "django.middleware.clickjacking.XFrameOptionsMiddleware",]
ROOT_URLCONF = "watchtower.urls"
WSGI_APPLICATION = "watchtower.wsgi.application"
LANGUAGE_CODE = "en-us"
TIME_ZONE = "UTC"
USE_I18N = true
USE_L10N = true
USE_TZ = true
STATIC_URL = "/static/"
LOAD_DOTENV = true
DEFAULT_SETTINGS_PATHS = [ "settings.py", "settings.toml", "settings.tml", "settings.yaml", "settings.yml", "settings.ini", "settings.conf", "settings.properties", "settings.json", ".secrets.py", ".secrets.toml", ".secrets.tml", ".secrets.yaml", ".secrets.yml", ".secrets.ini", ".secrets.conf", ".secrets.properties", ".secrets.json",]
[[development.TEMPLATES]]
BACKEND = "django.template.backends.django.DjangoTemplates"
DIRS = []
APP_DIRS = true

[development.TEMPLATES.OPTIONS]
context_processors = [ "django.template.context_processors.debug", "django.template.context_processors.request", "django.contrib.auth.context_processors.auth", "django.contrib.messages.context_processors.messages",]
[[development.AUTH_PASSWORD_VALIDATORS]]
NAME = "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"

[[development.AUTH_PASSWORD_VALIDATORS]]
NAME = "django.contrib.auth.password_validation.MinimumLengthValidator"

[[development.AUTH_PASSWORD_VALIDATORS]]
NAME = "django.contrib.auth.password_validation.CommonPasswordValidator"

[[development.AUTH_PASSWORD_VALIDATORS]]
NAME = "django.contrib.auth.password_validation.NumericPasswordValidator"

[development.DATABASES.default]
ENGINE = "django.db.backends.sqlite3"
NAME = "/Users/ouss/Documents/workspace/Watchtower/watchtower/db/db.sqlite3"